# Generated by Django 3.0.4 on 2021-12-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211217_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_sk_sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('dataframe', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='software_engineer_sk_sum',
            new_name='cloud_architect_sk_annual',
        ),
        migrations.RenameModel(
            old_name='Web_developer_sk_sum',
            new_name='data_analyst_sk_annual',
        ),
        migrations.RenameModel(
            old_name='cloud_architect_sk_sum',
            new_name='network_engineer_sk_annual',
        ),
        migrations.RenameModel(
            old_name='network_engineer_sk_sum',
            new_name='software_engineer_sk_annual',
        ),
        migrations.RenameModel(
            old_name='data_analyst_sk_sum',
            new_name='Web_developer_sk_annual',
        ),
    ]
