# Generated by Django 3.0.4 on 2021-12-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211217_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_sk_sum',
            name='post',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position_sk_sum',
            name='dataframe',
            field=models.CharField(max_length=500),
        ),
    ]
