# Generated by Django 3.0.4 on 2021-12-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211218_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position_sk_post_sum',
            name='id',
        ),
        migrations.AlterField(
            model_name='position_sk_post_sum',
            name='position',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
