# Generated by Django 3.0.4 on 2022-01-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_analyst_programmer_sk_annual_developer_programmer_sk_annual_ict_security_specialist_sk_annual_ict_su'),
    ]

    operations = [
        migrations.DeleteModel(
            name='network_analyst_sk_annual',
        ),
    ]
