# Generated by Django 3.0.4 on 2022-01-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_network_analyst_sk_annual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloud_architect_sk_annual',
            old_name='Amount',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='data_analyst_sk_annual',
            old_name='Amount',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='network_engineer_sk_annual',
            old_name='Amount',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='software_engineer_sk_annual',
            old_name='Amount',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='web_developer_sk_annual',
            old_name='Amount',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='cloud_architect_sk_annual',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='cloud_architect_sk_annual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='data_analyst_sk_annual',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='data_analyst_sk_annual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='network_engineer_sk_annual',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='network_engineer_sk_annual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='software_engineer_sk_annual',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='software_engineer_sk_annual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='web_developer_sk_annual',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='web_developer_sk_annual',
            name='id',
        ),
        migrations.AddField(
            model_name='cloud_architect_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='cloud_architect_sk_annual',
            name='month',
            field=models.CharField(default='none', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='data_analyst_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='data_analyst_sk_annual',
            name='month',
            field=models.CharField(default='none', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='network_engineer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='network_engineer_sk_annual',
            name='month',
            field=models.CharField(default='none', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='software_engineer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='software_engineer_sk_annual',
            name='month',
            field=models.CharField(default='none', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='web_developer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='web_developer_sk_annual',
            name='month',
            field=models.CharField(default='none', max_length=100, primary_key=True, serialize=False),
        ),
    ]
