# Generated by Django 3.0.4 on 2022-01-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220117_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='none', max_length=50)),
                ('Released_Date', models.CharField(default='none', max_length=20)),
                ('URL', models.CharField(default='none', max_length=100)),
                ('SpecificT', models.CharField(default='none', max_length=30)),
                ('Tags', models.CharField(default='none', max_length=30)),
            ],
        ),
    ]
