# Generated by Django 3.0.4 on 2022-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20220206_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst_programmer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='cloud_architect_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='data_analyst_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='developer_programmer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='ict_security_specialist_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='ict_support_engineer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='network_administrator_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='network_engineer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='position_sk_post_sum',
            name='dataframe',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='software_engineer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='software_tester_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
        migrations.AlterField(
            model_name='web_developer_sk_annual',
            name='dataframe',
            field=models.CharField(default='none', max_length=1500),
        ),
    ]
